// Column definitions + sample rows for Excel import templates
export const IMPORT_CONFIGS = {
  suppliers: {
    title: "Import Suppliers",
    endpoint: "/api/import/suppliers",
    columns: [
      { key: "name", label: "Name", required: true },
      { key: "contactPerson", label: "Contact Person" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone" },
      { key: "country", label: "Country" },
      { key: "city", label: "City" },
      { key: "category", label: "Category" },
      { key: "paymentTerms", label: "Payment Terms" },
      { key: "status", label: "Status" },
      { key: "rating", label: "Rating" },
    ],
    sample: {
      Name: "Emirates Industrial Supplies LLC", "Contact Person": "Khalid Al Mansoori",
      Email: "khalid@emiratesindustrial.com", Phone: "+971 4 555 1234",
      Country: "UAE", City: "Dubai", Category: "Electrical",
      "Payment Terms": "Net 30", Status: "Active", Rating: 5,
    },
  },
  products: {
    title: "Import Products",
    endpoint: "/api/import/products",
    columns: [
      { key: "sku", label: "SKU", required: true },
      { key: "name", label: "Name", required: true },
      { key: "category", label: "Category" },
      { key: "unit", label: "Unit" },
      { key: "supplier", label: "Supplier" },
      { key: "unitCost", label: "Unit Cost" },
      { key: "lastPurchasePrice", label: "Last Purchase Price" },
      { key: "stockQty", label: "Stock Qty" },
      { key: "reorderLevel", label: "Reorder Level" },
      { key: "status", label: "Status" },
    ],
    sample: {
      SKU: "ELC-001", Name: "Copper Cable 2.5mm (100m)", Category: "Electrical", Unit: "Roll",
      Supplier: "Emirates Industrial Supplies LLC", "Unit Cost": 185, "Last Purchase Price": 192.5,
      "Stock Qty": 120, "Reorder Level": 25, Status: "Active",
    },
  },
  leads: {
    title: "Import Leads",
    endpoint: "/api/import/leads",
    columns: [
      { key: "companyName", label: "Company Name", required: true },
      { key: "contact", label: "Contact" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone" },
      { key: "productOffered", label: "Product Offered" },
      { key: "quotedPrice", label: "Quoted Price" },
      { key: "source", label: "Source" },
      { key: "status", label: "Status" },
      { key: "notes", label: "Notes" },
      { key: "followUpDate", label: "Follow Up Date" },
    ],
    sample: {
      "Company Name": "Hangzhou EcoPack Solutions", Contact: "Lucy Zhao",
      Email: "lucy.zhao@ecopack.com", Phone: "+86 571 555 8899",
      "Product Offered": "Biodegradable packaging film", "Quoted Price": 38.5,
      Source: "Exhibition", Status: "New", Notes: "Met at Gulfood Manufacturing",
      "Follow Up Date": "2026-06-20",
    },
  },
  invoices: {
    title: "Import Invoices",
    endpoint: "/api/import/invoices",
    columns: [
      { key: "invoiceNo", label: "Invoice No", required: true },
      { key: "supplier", label: "Supplier", required: true },
      { key: "poNumber", label: "PO Number" },
      { key: "invoiceDate", label: "Invoice Date" },
      { key: "dueDate", label: "Due Date" },
      { key: "amount", label: "Amount" },
      { key: "currency", label: "Currency" },
      { key: "status", label: "Status" },
    ],
    sample: {
      "Invoice No": "INV-2026-0101", Supplier: "Emirates Industrial Supplies LLC",
      "PO Number": "", "Invoice Date": "2026-06-01", "Due Date": "2026-07-01",
      Amount: 12500, Currency: "AED", Status: "Pending",
    },
  },
};
